services:
  photo-recette:
    image: ghcr.io/jhenninot/photo-recette-mealie:latest
    container_name: photo-recette-mealie
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
